name: flutter_basics
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Yeongdo
      fonts:
        - asset: assets/fonts/Yeongdo/Yeongdo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Yeongdo/Yeongdo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Yeongdo/Yeongdo-Heavy.ttf
          weight: 900
